[package]
name = "systemcontrol"
version = "0.1.1"
edition = "2024"

[dependencies]
zbus = "5.15.0"
descape = "3.0.0"

[dependencies.eframe]
version = "0.34.2"
default-features = false
features = ["wayland", "wgpu", "default_fonts"]

[profile.release]
strip = true
lto = "fat"
opt-level = "s"
panic = "abort"
